ghostty-org/discord-bot

app/components/docs.py
=> fix: skip page autocomplete if section wasn't filled out

app/components/entity_mentions.py
Fixes #103. We can finally ignore these now that discussions work.
=> fix: ignore unknown entity mentions

README.md
Closes #109. The rendered view can be checked here: https://github.com/ghostty-org/discord-bot/blob/documentation/README.md
=> docs: add project documentation

app/components/entity_mentions.py
Even if it isn't one that is in response to a message of theirs.
=> Allow moderators to delete any entity mention

app/components/docs.py, app/components/entity_mentions/__init__.py, app/components/entity_mentions/cache.py, app/components/entity_mentions/discussions.py, app/components/entity_mentions/fmt.py, app/setup.py, nix/python-app.nix, poetry.lock, pyproject.toml
Draft, trying to figure out how to make Nix like this change
=> build: replace `pygithub` with `githubkit`

app/components/message_filter.py, app/utils.py
Addresses https://github.com/ghostty-org/discord-bot/pull/124#discussion_r1911944655
=> refactor: add a util for packing long messages into attachments

.github/workflows/ruff.yml, flake.nix, nix/devshell.nix, nix/overlay.nix, nix/package.nix, nix/python-app.nix
- Adds in alejandra to devShell
- Formaat all existing nix code
- Check for formatting in CI code
=> build(nix): add alejandra and formatting nix code to CI

app/components/entity_mentions/fmt.py
=> fix: gracefully handle fetch fails

app/components/entity_mentions/__init__.py, app/components/entity_mentions/cache.py, app/components/entity_mentions/fmt.py, app/components/entity_mentions/resolution.py
=> feat: allow mentioning entities from any GitHub repo

app/components/__init__.py, app/components/autoclose.py, app/components/docs.py, app/components/entity_mentions/fmt.py, app/components/status.py, app/core.py, app/utils/__init__.py
=> feat: add a bot status command

app/components/entity_mentions/fmt.py, app/utils/__init__.py, app/utils/webhooks.py
Continuation of #157, thank you GitHub.
Closes the first part of #155.
=> Move nitro emojis

.github/workflows/ci.yml, README.md, app/components/close_help_post.py, app/components/docs.py, app/components/entity_mentions/integration.py, app/components/message_filter.py, app/components/move_message.py, app/components/zig_codeblocks.py, pyproject.toml, uv.lock
Continuation of #175, rationale at https://github.com/ghostty-org/discord-bot/pull/175#issuecomment-2697073739.
=> Add Pyright

app/utils/webhooks.py
Continuation of #159, thank you GitHub.
Closes section 6.3 of #155.
=> Ignore polls that have ended

app/utils/__init__.py, app/utils/message_data.py, app/utils/webhooks.py
=> Include the moved message's timestamp

app/components/entity_mentions/models.py
=> Reduce the number of regexes used

app/components/move_message.py, app/utils/__init__.py, app/utils/webhooks.py
Continuation of #180, because I accidentally deleted the branch momentarily, sorry @trag1c.
Closes sections 5 and 6 of #155.
See #180 for the (now finished) check list.
=> Move replies, forwards and interactions, and disallow moving system messages

README.md, app/components/entity_mentions/fmt.py, app/components/entity_mentions/resolution.py
Recreation of #44.  I can't figure out when this was removed.
=> Name linked entities again

README.md
Resolves task two of #153.
There isn't a lot of text, but I really don't know what there is to say about these features other than a quick mention.
=> Cover closing and locking #help posts in the README

app/components/status.py
=> Don't die on very early status requests

app/components/lock_old_posts.py
Some very DRY timestamp crackers… and puns so bad people are crackl- I mean, cackling…
Motivated by the second computation of this timestamp after the introduction of https://github.com/ghostty-org/discord-bot/commit/1da7a6dcce57def33f3d38beb7d469b9b8421d7b.
I've also snuck a comment about https://github.com/ghostty-org/discord-bot/commit/1da7a6dcce57def33f3d38beb7d469b9b8421d7b in there as well.
=> Store the lock threshold in a variable

README.md, app/components/entity_mentions/resolution.py, app/components/xkcd_mentions.py, app/core.py, app/utils/hooks.py
=> Add support for XKCD mentions

app/components/github_integration/comments/discussions.py, app/components/github_integration/comments/fetching.py, app/components/github_integration/mentions/discussions.py
=> github-integration: split discussions module

app/components/docs.py, app/components/move_message.py, app/components/zig_codeblocks.py, app/utils/__init__.py
Hopefully it works with Python 3.12 too, I'm too lazy to compile another copy.
=> Prefer `typing.Self`

app/utils/webhooks.py
<details><summary>Before…</summary>
</details>
<details><summary>After…</summary>
</details>
=> Improve moved message sticker embeds

.env.example
I split this out of #219 but appear to have forgotten to PR it.
=> Add a hint about things to update when changing `.env.example`

app/utils/webhooks.py
Based on #226; merge that first.
=> Remove reactions from moved forwards

app/components/lock_old_posts.py
Instead of waiting for the auto-close task to get to them a day later.
=> Also close old locked posts that were locked

tests/test_meta.py
Fixes https://github.com/ghostty-org/discord-bot/pull/242#discussion_r2149870775.
Maybe I should make it more serious/formal…
=> Explain why VS16s are flagged as problematic

app/components/github_integration/comments/integration.py, app/components/move_message.py, app/components/zig_codeblocks.py, app/utils/__init__.py, app/utils/webhooks.py, tests/test_meta.py
=> add a safeguard for accidental VS16 additions

.env.example, app/components/close_help_post.py, app/components/docs.py, app/components/github_integration/code_links.py, app/components/github_integration/comments/discussions.py, app/components/github_integration/comments/fetching.py, app/components/github_integration/comments/integration.py, app/components/github_integration/mentions/resolution.py, app/components/github_integration/models.py, app/components/lock_old_posts.py, app/components/message_filter.py, app/components/move_message.py, app/components/status.py, app/components/zig_codeblocks.py, app/utils/__init__.py, app/utils/hooks.py, app/utils/message_data.py, app/utils/webhooks.py, tests/test_message_moving.py
Based on #262, merge that first.
Re conversation on Discord.
=> Hard-wrap all comments and strings to 88 characters wide

app/utils/webhooks.py
=> Assorted cleanup from MessageSnapshot change

app/common/hooks.py, app/common/message_moving.py, app/components/accept_invite.py, app/components/autoclose.py, app/components/close_help_post.py, app/components/docs.py, app/components/github_integration/code_links.py, app/components/github_integration/comments/integration.py, app/components/github_integration/mentions/fmt.py, app/components/github_integration/mentions/integration.py, app/components/github_integration/mentions/resolution.py, app/components/lock_old_posts.py, app/components/message_filter.py, app/components/move_message.py, app/components/xkcd_mentions.py, app/components/zig_codeblocks.py, app/core.py, app/setup.py, app/utils/__init__.py, app/utils/message_data.py, tests/test_message_moving.py, tests/test_utils.py
Supersedes #281.
Re discussion on Discord.
=> Alias `discord` as `dc`

app/components/zig_codeblocks.py
Closes #277. Yes it was that simple.
=> zig-codeblocks: allow replacing messages with attachments

app/common/hooks.py, pyproject.toml, tests/conftest.py, tests/fixtures/__init__.py, tests/fixtures/hooks.py, tests/hooks/test_delete_hook.py, tests/hooks/test_edit_hook.py, tests/hooks/test_message_linker.py, tests/hooks/utils.py, tests/test_message_moving.py
=> add edit/delete hook and message linking tests

app/common/hooks.py, app/components/github_integration/code_links.py, app/components/github_integration/comments/integration.py, app/components/github_integration/mentions/integration.py, app/components/xkcd_mentions.py, app/components/zig_codeblocks.py, app/utils/__init__.py
=> re-suppress embeds after 5 seconds

app/common/hooks.py, app/components/github_integration/mentions/integration.py, app/components/move_message.py, app/utils/__init__.py
=> add safeguards for editing messages in update task

app/components/github_integration/__init__.py, app/components/github_integration/commits.py, app/components/github_integration/mentions/fmt.py, app/components/github_integration/mentions/integration.py, app/components/github_integration/mentions/resolution.py, app/components/github_integration/models.py, app/core.py
=> support linking commits from SHAs

app/components/github_integration/code_links.py, app/components/github_integration/comments/fetching.py
This regex is the same as for commits and mentions.
This redoes #238, but better.
=> Make the owner and repo matches in regexes stricter

app/components/github_integration/commits.py
=> support URLs as commit mention source; don't trigger for code links

app/components/github_integration/comments/fetching.py, app/components/github_integration/models.py, app/components/github_integration/webhooks/discussions.py, app/components/github_integration/webhooks/issues.py, app/components/github_integration/webhooks/prs.py
not the biggest fan of how I fixed promoted discussion formatting but it works:
=> webhooks: fix some formatting issues + add `GitHubUser.default`

app/components/github_integration/webhooks/prs.py
Right now when someone replies to a review thread, a webhook feed will include these two messages:
This is because all review thread comments are actually parts of reviews under the hood. This PR changes the behavior to ignore those review events.
=> webhooks: ignore empty reviews

app/__main__.py, app/common/cache.py, app/common/hooks.py, app/common/message_moving.py, app/components/autoclose.py, app/components/github_integration/code_links.py, app/components/github_integration/comments/fetching.py, app/components/github_integration/comments/integration.py, app/components/github_integration/commits.py, app/components/github_integration/mentions/cache.py, app/components/github_integration/mentions/fmt.py, app/components/github_integration/mentions/integration.py, app/components/github_integration/mentions/resolution.py, app/components/github_integration/models.py, app/components/move_message.py, app/components/xkcd_mentions.py, app/components/zig_codeblocks.py, app/setup.py, app/utils/message_data.py, pyproject.toml, tests/fixtures/hooks.py, tests/utils/kitposer.py
=> use `recommended` mode for basedpyright

pyproject.toml, uv.lock
Closes #315
See the changelogs for a full idea of what new features exist / bug fixes implemented https://discordpy.readthedocs.io/en/stable/whats_new.html#v2-6-0
Tested that things still work as expected. However, I do not have a full test suite checklist to ensure that actually all edge cases are still working as expected.
=> chore: bump dpy version

app/components/github_integration/webhooks/discussions.py
Brought up by Kat on Discord (thanks!). The screenshot below is the current behavior. The new behavior has the second embed not include the body + the embed author is the answer chooser rather than the answerer (happens to be the same person in this example).
=> webhooks: adjust discussion.answered to better work with comments

app/bot.py, app/components/github_integration/commits.py, app/status.py, app/utils/__init__.py, tests/test_utils.py
=> Show a commit link for the commit in `/status`

app/common/message_moving.py, app/components/close_help_post.py
=> Allow the author of a moved help post to `/close` it

app/__main__.py, app/bot.py, app/common/cache.py, app/common/linker.py, app/components/accept_invite.py, app/components/developer.py, app/components/github_integration/commits.py, app/errors.py, app/log.py, app/utils/__init__.py, app/utils/message_data.py, pyproject.toml, tests/test_utils.py
Follow-up to #313.
The following are done:
- Everything in utils.
- Everything in common except `message_moving.py`.
- Every file (not directory) under `app`.
- `components/developer.py` and `components/accept_invite.py`.
These are just some of the easier ones, I'm going to continue with the other components but I just wanted to open a PR of what I have right now.
Log levels and messages open to bikeshedding, of course.
=> Add assorted log messages

app/components/github_integration/mentions/integration.py
This isn't done for anything else.
=> Remove warning for entity mentions in DMs

app/bot.py, app/components/github_integration/comments/discussions.py, app/components/github_integration/entities/discussions.py, app/components/github_integration/entities/fmt.py, app/components/github_integration/models.py, app/components/github_integration/webhooks/discussions.py, tests/test_close_help_post.py
Closes #380
Added:
* discussion_duplicate
* discussion_outdated
Supported in webhooks and entities
=> feat: add more discussion state emojis
