app/components/move_message.py

A username like `_therealmitchellh_` would show up as italics, and something like `thereal_mitchellh_` would be even more confusing since only a part of it is in italics.

Escape underscores in username when ghost-pinging

---

app/components/docs.py

Closes #97.
In particular:
* `vt/` subsections:
* `vt-concepts`
* `vt-control`
* `vt-csi`
* `vt-esc`
* `keybind` (linking to [Overview](https://ghostty.org/docs/config/keybind), [Trigger Sequences](https://ghostty.org/docs/config/keybind/sequence), etc.)
* `config` (linking to [Overview](https://ghostty.org/docs/config) etc.)
Unintentionally, there are now a few ways to get the same page, e.g. `(config, keybind)` and `(keybind, overview)` both lead to https://ghostty.org/docs/config/keybind.

feat: improve `/docs` command

---

app/components/entity_mentions.py
app/core.py

Closes #120
Before | After
------ | -----
This requires (there's a fallback mechanism though) that the server has the required emojis beforehand (and all names must match to those in `EMOJI_NAMES`).\
The emoji pack: [emojis.zip](https://github.com/user-attachments/files/18330509/emojis.zip)
The bot will now also give a heads up if any mentions were omitted from the final message.
* mentioning a PR for the first time takes slightly longer because the bot needs to do a second request (until now we checked if an entity is a PR by checking the `Issue.pull_request` field...)
* all of this new formatting doesn't allow for as many mentions in one message (one entity now takes over twice as many bytes <sub>(hence the "After" screenshot needing 2 messages)</sub>), but it's not a huge deal as …

feat: revamp entity mentions

---

app/utils.py

fix: attach message content if too long when moving

---

README.md
app/components/message_filter.py
app/utils.py

Closes #119
If the deleted message had any content, the bot will send it back to the user with the notification (it sends 3 messages so it's easier to use the "Copy Text" thing, but 2 of them are silent so the sound plays just once).
The behavior for no content is unchanged (the message below the red line wasn't cropped 😉).

feat: send back the message content when filtered

---

nix/python-app.nix

I can revert the formatting if thats desired.

fix(nix): Add hatch-fancy-pypi-readme to hishel build inputs 

---

app/components/entity_mentions/cache.py
app/components/entity_mentions/discussions.py
app/components/entity_mentions/fmt.py
app/components/entity_mentions/integration.py

Built on top of #129. The wait time decreases significantly when multiple entities are mentioned for the first time in a message:

perf: improve entity fetching flow

---

app/components/entity_mentions/fmt.py

Closes #139, based on #142.
I'm not convinced it looks better, though.  In particular, I'm not partial to the grey background applied to timestamps; it does not fit in with the rest of the subtext.
<sup>**First**: before. **Second**: only `:D`. **Third**: `:D` with `:R` in brackets; i.e. this PR[^1].</sup>
[^1]: Note: I took this screenshot before I switched from targetting the [`main`] branch to the [`global-entity-mentions`] branch from #142.
[`main`]: https://github.com/ghostty-org/discord-bot/tree/main
[`global-entity-mentions`]: https://github.com/ghostty-org/discord-bot/tree/global-entity-mentions

Use a Discord timestamp for entity mention dates

---

app/components/__init__.py
app/components/entity_mentions/__init__.py
app/components/entity_mentions/integration.py
app/components/zig_codeblocks.py
app/core.py
app/utils.py
pyproject.toml
uv.lock

Closes #137. This relies on my https://github.com/trag1c/zig-codeblocks project.
Still left to do:

feat: add Zig syntax highlighting

---

app/components/close_help_post.py

Continuation of #151, thank you GitHub.
Before this change, if the new title was longer than 100 characters, an exception would be raised.
This is *very* hacky and probably the worst code I've ever PR'd.  Perhaps "Unable to change the post title." should be returned without all that effort to show the error from the Discord API; I can change the PR to do so if requested, though I would prefer to have the nicer message so the user of the command actually knows what happened.

Handle long help post titles gracefully

---

app/components/entity_mentions/fmt.py
app/components/entity_mentions/integration.py
app/utils/__init__.py

Closes #149.
Continuation of #156, thank you GitHub.

Sanitize markdown in GitHub entity titles

---

app/utils/webhooks.py

https://discord.com/channels/1005603569187160125/1320881498848497755/1346989561107972168

Improve the error message when the bot guild name does not contain `ghostty`

---

app/components/__init__.py
app/components/activity_status.py
app/core.py

Continuation of #173, thanks as usual GitHub 🙄.
It only takes so long for a bike shed to be flooded with string (that is, I expect the exact string to be bikeshed).
I tried setting the timestamp to when the bot started up, but for some reason Discord did not like it and it didn't show up anywhere.
Edit: quick note, if your suggestion starts with `Playing`, `Streaming`, `Listening to`, `Watching` or `Competing in`, it'll can be a special status, otherwise it'll just be the average custom status that shows up in a thought bubble on the profile.

Add an activity status

---

app/components/entity_mentions/cache.py
app/components/entity_mentions/code_links.py
app/components/entity_mentions/comments/fetching.py
app/components/entity_mentions/resolution.py
app/utils/__init__.py
app/utils/cache.py

1. Made the TTRCache splat its arguments to timedelta.
2. Moved it to `utils/` as I expect it would be useful outside of `entity_mentions` too (e.g., for #183).
I recommend viewing every commit individually, as it makes it more clear what changed than if you only look at the final diff.

Small changes to TTRCache

---

README.md
app/components/docs.py

Closes #194.
Also handles messages that are too long.  This affects both the interaction[^1] and the webhook paths, but I only noticed it now and don't want to make a new PR; plus you can't get 2000 characters without specifying `message`.
[^1]: It is still possible to get the interaction response with `message` specified in some specific channel types (such as voice channels).

Use a webhook for /docs

---

app/components/entity_mentions/resolution.py

Fixes #200.
Ironic how it's [number 200] when the issue is anything *but* okay :P.
[number 200]: https://http.cat/200

Avoid reacting with entity mentions on an entity comment link

---

app/components/autoclose.py
app/components/lock_old_posts.py
app/core.py
app/utils/__init__.py

Closes #174.
A known issue is that sending multiple messages in quick succession will trigger multiple responses, but I do not know of any clean way to work around this as the Discord API is not the fastest thing in the world, and this operation is inherently racy.
Documentation update: #197.

Lock old posts to discourage necroposting

---

app/components/entity_mentions/code_links.py

Heard you like printf-style string interpolation once, so here's an alternate diff :P /s:
<details>
<summary>Click or tap to display spoilered content.</summary>
```diff
diff --git a/app/components/entity_mentions/code_links.py b/app/components/entity_mentions/code_links.py
index 0d17340727..0db7ac3873 100644
--- a/app/components/entity_mentions/code_links.py
+++ b/app/components/entity_mentions/code_links.py
@@ -89,16 +89,42 @@
def _format_snippet(snippet: Snippet) -> str:
-    range_info = (
-        f"lines {snippet.range.start + 1}–{snippet.range.stop}"  # noqa: RUF001
-        if snippet.range.stop > snippet.range.start + 1
-        else f"line {snippet.range.start + 1}"
-    )
-    unquoted_path = urllib.parse.unquote(snippet.path)
return (
-        f"`{unquoted_path}`, …
```

Add hyperlinks to all relevant parts of the code links message

---

app/components/entity_mentions/code_links.py

An *incredibly* easy to discover feature that totally didn't require me to assault the code viewer with a large assortment of clicks /s.
Select some text, then click on the gutter in the selected range, to get one of these URLs for testing; e.g.: select some text between lines 5 and 9, then click on the gutter on lines 5, 6, 7, 8, or 9.  If you click outside the range the selection will be deselected; annoying, I know.
A test link: https://github.com/openSUSE/fonts-config/blob/master/59-family-prefer-lang-specific-cjk.conf#L337C1-L341C45.
These are just ignored in the regular expression as it's not possible to highlight the specific characters without pulling out tree-sitter with `ansi` highlighting again.

Handle character ranges in code links

---

app/components/entity_mentions/code_links.py
app/components/entity_mentions/comments/fetching.py
app/components/entity_mentions/resolution.py

GitHub just redirects it back to github.com, but these links *are* theoretically possible, similar to the http:// case.
Reject at one's own discretion.  This probably shouldn't be merged first since it would probably conflict with other, more important PRs.

Handle www.github.com

---

app/components/github_integration/code_links.py

Based on #207, merge that first.
This heuristic prefers false negatives over false positives.  Making an entire request to GitHub just for this one small thing seems wasteful, so there will definitely be cases where branches are considered revisions.  Maybe we have this information already; I'm not too familiar with GitHub's API.

Differentiate between branches and revisions

---

app/utils/message_data.py
app/utils/webhooks.py

As well as a few other assorted half-related commits >.>; I didn't want to make an entirely new PR for them.
Here's the image for commit two:

Handle Nitro reactions in moved messages

---

pyproject.toml
uv.lock

0.12.10 shipped a fix for yanyongyu/githubkit#200 where some PRs with null heads couldn't be mentioned (e.g. #1).

deps: bump githubkit to 0.12.11

---

app/components/github_integration/models.py

github-integration: prefer html_url over url for user models

---

app/utils/webhooks.py

I think I said I don't want to do this because then I have to make sure I don't go above the limit, but it's so easy I think I'll do it anyway.
**Before**:
(P.S.: this was slightly fabricated since I don't actually have Nitro; this message goes above the limit and hence would remain unchanged even after this change.)
**After**:
Which matches the output of moved messages that are not forwards.
Despite what you see above, if the emoji is from the current server, either animated or otherwise, it will be used directly:
The “After” screenshot doesn't display it like this because I had to make minor changes to the code to capture a screenshot for demonstration (as I don't actually have Nitro).

Handle Nitro emojis in forwards

---

app/components/github_integration/mentions/resolution.py

People frequently try `website` instead of `web`, and while we're at it why not give bias to ghostty-org repositories ;D.

More mention aliases

---

app/utils/webhooks.py

A better way to do this would be `(e for e in m.embeds if e.url not in m.content)`, but that breaks in the presence of redirects, which is very common with YouTube links.

Only move bot embeds

---

app/components/accept_invite.py
app/components/github_integration/mentions/fmt.py
app/utils/webhooks.py

With the exception of ⚡️ on some systems and applications, all other changes look like nothing changed; use a hex editor or something similar to view the changes.
-----
The following text is a modified and slightly reduced[^1] Markdown version of the commit message.
Note: all hex sequences below are for text encoded in UTF-8, which is the character encoding this text should have be encoded as, assuming GitHub doesn't do weird nonsense and make it UTF-16.
There are multiple ways to represent the same code-point in Unicode, and these variations are controlled with “Variation Selectors” (there are 16 of these, and they have their own block). The relevant ones here are:
- just the base code-point (no variation selector): 👍 (f09f 918d);
- the text variation selector (VS-15): 👍︎ (f09f 918d efb8 …

Remove unnecessary emoji variation selectors / Always use Discord SVG emojis

---

app/components/github_integration/code_links.py
app/components/github_integration/comments/integration.py
app/components/xkcd_mentions.py
app/utils/hooks.py

I only special-case one code link as the context would then be directly above the file:
If it were done for all cases, the correspondence between contexts and files would not be apparent as the files are necessarily displayed at the end.
While I *could* do it for the last blob that causes the limit to be exceeded, that might end up being a two line snippet (for example); putting something that small in a file is odd.

Attach some long code links in files

---

app/components/message_filter.py
app/components/zig_codeblocks.py

It's not right click on mobile, it's long press. And “context menu” reads more fluently than “right click or long press”.

Avoid referring to the context menu as a “right click” menu

---

app/utils/webhooks.py

I had this in mind when I was halfway through writing `SplitSubtext`, but then proceeded to forget, oops…

Correctly handle moving moved messages with no content

---

app/components/github_integration/models.py

#250 added a list and the comments code does a `not in` which needs `Issue` to be hashable.

Fix GitHub comments

---

app/utils/__init__.py
app/utils/message_data.py
app/utils/webhooks.py

Closes #259.
This fixes forwards from servers the bot is not in.

Use `MessageSnapshot` instead of fetching forwarded messages

---

app/components/github_integration/comments/fetching.py

GitHub's UI uses it when multiple people or teams were requested for a review, but the event URL only ever refers to one such person/team, so special-casing the correct usage will never end up being shown.
Re convo on Discord.

Remove special-casing of `a` before `review` in comments

---

app/components/github_integration/mentions/fmt.py

Closes #278. Looks like GitHub just expires some diffs (I'd guess deleted forks) after some time:
```
λ curl "https://patch-diff.githubusercontent.com/raw/ghostty-org/ghostty/pull/1234.patch"
Sorry, this diff is unavailable.
```
```
λ curl "https://patch-diff.githubusercontent.com/raw/ghostty-org/ghostty/pull/7149.patch"
From d4525f2c575b48553499b58d4e680e139dcc36ab Mon Sep 17 00:00:00 2001
From: Kat <65649991+00-kat@users.noreply.github.com>
Date: Mon, 21 Apr 2025 03:41:52 +0000
Subject: [PATCH] Correct remaining instances of `change_title_prompt` to
`prompt_surface_title`.
---
macos/Sources/App/macOS/AppDelegate.swift | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
diff --git a/macos/Sources/App/macOS/AppDelegate.swift b/macos/Sources/App/macOS/AppDelegate.swift
index …
```

hide empty diff sizes for PR mentions

---

app/components/zig_codeblocks.py

Resolves #274
This PR only applies the discord work around from within the codeblocks. This is the cleanest solution I could come up with, without modifying the upstream library. 
Thing to note, I also made it only change code inside ANSI codeblocks. Don't want to do the sub on "multi codeblock" messages.
Example:
````md
In python `2 // 3` is 0 and 2 in zig
```py
2 // 3
```
Outputs 0
```zig
2 // 3
```
Outputs 2
hi! // hello!!
```py
```
````

fix: SGR 0 only applied inside codeblocks

---

app/components/close_help_post.py

`/close wontfix` is often used for upstream issues so this makes the intent more obvious.

Add `/close upstream` as an alternative to `/close wontfix`

---

app/components/github_integration/webhooks/__init__.py
app/components/github_integration/webhooks/core.py
app/components/github_integration/webhooks/prs.py
pyproject.toml
uv.lock

The following events are now supported:
* PRs:
* (re)opened
* closed/merged
* edited
* (un)drafted
* (un)locked
* PR reviews:
* (un)requested
* submitted/dismissed
* comment created (review comments, not regular comments, that's gonna be covered by an issues PR)

webhook: handle PR events

---

app/components/github_integration/webhooks/__init__.py
app/components/github_integration/webhooks/discussions.py

The following discussion events are now supported:
* (re)opened/closed
* (un)pinned
* (un)locked
* (un)answered
There are quite a few improvements to be made to the code (not just this module, I mean the entire webhook feature) and there are a few minor features I'd like to add/improve, but I think it's in a good state to ship and get some initial feedback (so that any tweaks can be better coordinated).

webhooks: handle discussion events

---

.github/workflows/ci.yml
README.md
justfile
pyproject.toml

This PR simplifies the format setting, putting format in preview mode through the config file instead of the CLI.
The motivation for this, is two things. A) allows for consistent command CLI usage in all projects (regardless of if your project uses preview mode or not) and B) enables consistent rule definition in a single location. Easy to get out of preview mode later.

chore: remove need for explicit preview flag

---

app/components/github_integration/webhooks/issues.py
app/components/github_integration/webhooks/prs.py

This is almost a 1:1 copy of `pull_request.edited`. I'm looking to DRY this out when I get around to using `difflib`.

webhooks: support `issues.edited`

---

.github/workflows/ci.yml
pyproject.toml
uv.lock

A little maintenance on the dependencies
For bot itself:
```
Update basedpyright v1.31.3 -> v1.31.4
Update sentry-sdk v2.35.0 -> v2.36.0
Update typing-extensions v4.14.1 -> v4.15.0
```
For CI:
```
Update uv 0.7.16 -> 0.8.15
Update setup-uv v6.5.0 -> v6.6.1
```

chore: bump dependencies

---

app/common/message_moving.py
app/components/move_message.py
app/components/zig_codeblocks.py

I do not see any point to specifying that it uses a webhook to move the message when you already pass the webhook as a parameter. If this change isn't considered desirable, feel free to close the PR.

Rename move_message_via_webhook() to move_message()

---

app/components/github_integration/comments/fetching.py

Example: `https://github.com/google-gemini/gemini-cli/pull/4625#event-19668902591` (inline code to avoid spamming their issue tracker).

Support `removed_from_merge_queue`

---

app/components/activity_status.py
app/components/github_integration/__init__.py
app/components/github_integration/code_links.py
app/components/github_integration/comments/__init__.py
app/components/github_integration/comments/integration.py
app/components/github_integration/commits.py
app/components/github_integration/mentions/__init__.py
app/components/github_integration/mentions/integration.py
app/components/message_filter.py
app/components/xkcd_mentions.py
app/components/zig_codeblocks.py

Follow-up to #340.
`CodeLinks.code_linker` ⇒ `CodeLinks.linker`, and other similar renames.

Remove redundant affixes

---

app/components/lock_old_posts.py

Since it takes a few seconds for the post to actually be locked, the bot ends up replying to its own “open a new thread” message with another “open a new thread” message, as seen here: https://discord.com/channels/1005603569187160125/1398875640198987816/1417809020827471894.

Ignore bot messages when checking if a post is to be locked.

---

app/components/close_help_post.py

It is far easier to get the already loaded sitemap data to populate the autocomplete, than to memorize the config names or go to the site for the name. It is a low cost feature. 
Tested with docs cog not loaded too. You can also type whatever you want, so the command's logic to catch invalid options is still valid. Additionally, don't have to worry about desync between site and autocomplete, since that desync would cause an error anyway. IE, reference something that is on site but not `sitemap`.

feat: autocomplete solved config options

---

app/bot.py
app/components/github_integration/commits.py

Fixes #373
Call to load emojis in two places, ensuring that the emojis will be loaded when needed.

fix: loaded emoji race condition

---

.github/workflows/ci.yml
pyproject.toml
uv.lock

Some general dep maintenance. Nothing of note to report from any of these updates. 
```diff
- basedpyright==1.31.4
+ basedpyright==1.31.6
- githubkit==0.13.1
+ githubkit==0.13.3
- hypothesis==6.138.16
+ hypothesis==6.140.2
- nodejs-wheel-binaries==22.18.0
+ nodejs-wheel-binaries==22.20.0
- pydantic==2.11.7
+ pydantic==2.11.9
- pydantic-settings==2.10.1
+ pydantic-settings==2.11.0
- pytest==8.4.1
+ pytest==8.4.2
- ruff==0.13.0
+ ruff==0.13.3
- sentry-sdk==2.38.0
+ sentry-sdk==2.39.0
- typing-inspection==0.4.1
+ typing-inspection==0.4.2
```

bump dependencies

---

app/components/github_integration/commit_links.py

It's `not` everywhere else (e.g. `zig_codeblocks`, entity mentions). Also adds a missing first suppress.

Make zero item count check in commit links more consistent

---

app/components/developer.py

Re Discord.
-----
We exclusively run it in private channels anyway, and were it to be run outside (which hasn't happened yet), it would almost certainly be for demonstration purposes, where the sync message being a reply would be a better outcome.
The command ignores the case where a non-mod runs !sync, so all other users would not notice anything.

Reply instead of DM caller in `!sync`

---

app/components/github_integration/webhooks/commits.py
app/components/github_integration/webhooks/discussions.py
app/components/github_integration/webhooks/issues.py
app/components/github_integration/webhooks/prs.py
app/components/github_integration/webhooks/utils.py

Closes #387 
This PR cleans up embeds sent from webhook logic. This handles the `<sup>` and `<sub>` tags and shortens long GH links into hyperlinks, when possible and logical. This **does not** convert things like `#123` into a hyperlink.
Created issues might also have `div` tags that should be removed. A tag that comes from converting a discussion into an issue. It just takes up space that we can ignore on creation.

feat: auto cleanup webhooks
